### ISSUE TITLE
About transmitted data

### ISSUE THREAD

**Issue by 1616255** [KuskoSoft/FeitCSI#2]
Is it absolutely necessary for the RX to know the exact transmission data (e.g. through a repeating pattern “01010101”) so that the RX can distinguish between the transmission data and the influence of the environment?
Or does it not matter what information the transmitter sends, so that any data can be transmitted?

**Comment by KuskoSoft** [comment]
Hello @1616255 , it doesn't matter what information transmitter sends. The FeitCSI extract CSI from all overheard frames in set channel width, frequency and format.
